/** Portal-Copy (E7) — nur Deutsch. Ersetzt portal2/i18n/catalog.json. */

export const PORTAL_COPY = {
  bei_ruckfragen_erreichen_sie: "Bei Rückfragen erreichen Sie ",
  diese_nachricht_kann_nicht_beantwortet_werden: "Diese Nachricht kann nicht beantwortet werden.",
  schaden_melden: "Schaden melden",
  bitte_wahlen_sie_zunachst_das_betroffene_gebaude: "Bitte wählen Sie zunächst das betroffene Gebäude.",
  kategorie: "Kategorie",
  bereich: "Bereich",
  details: "Details",
  beschreibung: "Beschreibung",
  fotos: "Fotos",
  kontakt: "Kontakt",
  notfall: "Notfall",
  akute_gefahr_wasser_strom_sicherheit: "Akute Gefahr – Wasser, Strom, Sicherheit",
  schaden: "Schaden",
  etwas_ist_beschadigt_oder_defekt: "Etwas ist beschädigt oder defekt",
  reparatur: "Reparatur",
  etwas_funktioniert_nicht_richtig: "Etwas funktioniert nicht richtig",
  sonstiges: "Sonstiges",
  anderes_anliegen: "Anderes Anliegen",
  wasser_sanitar: "Wasser / Sanitär",
  heizung: "Heizung",
  strom_elektrik: "Strom / Elektrik",
  fenster_turen: "Fenster / Türen",
  dach: "Dach",
  schimmel_feuchte: "Schimmel / Feuchte",
  ja: "Ja",
  nein: "Nein",
  beschreiben_sie_das_problem_moglichst_genau: "Beschreiben Sie das Problem möglichst genau…",
  fotos_helfen_das_problem_schneller_einzuschatzen_optiona: "Fotos helfen, das Problem schneller einzuschätzen (optional).",
  foto: "Foto",
  name: "Name",
  e_mail: "E-Mail",
  telefon: "Telefon",
  wohneinheit_lage: "Wohneinheit / Lage",
  mit_dem_absenden_stimmen_sie_der_verarbeitung_ihrer_anga: "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer Angaben durch ",
  zur_bearbeitung_ihrer_meldung_zu: " zur Bearbeitung Ihrer Meldung zu.",
  zuruck: "Zurück",
  meldung_absenden: "Meldung absenden",
  weiter: "Weiter",
  meldung_eingegangen: "Meldung eingegangen",
  hat_ihre_meldung_erhalten_und_pruft_sie_sie_erhalten_ein: " hat Ihre Meldung erhalten und prüft sie. Sie erhalten eine Bestätigung per E-Mail.",
  referenznummer: "Referenznummer",
  status_verfolgen: "Status verfolgen",
  eingegangen: "Eingegangen",
  ihre_meldung_ist_bei_ihrer_verwaltung_eingegangen: "Ihre Meldung ist bei Ihrer Verwaltung eingegangen.",
  in_bearbeitung: "In Bearbeitung",
  ihre_verwaltung_bearbeitet_ihre_meldung: "Ihre Verwaltung bearbeitet Ihre Meldung.",
  bestatigung: "Bestätigung",
  ihre_verwaltung_hat_die_ausfuhrung_bestatigt_ein_fachbet: "Ihre Verwaltung hat die Ausführung bestätigt — ein Fachbetrieb ist beauftragt.",
  beauftragt: "Beauftragt",
  ein_fachbetrieb_wurde_von_ihrer_verwaltung_beauftragt: "Ein Fachbetrieb wurde von Ihrer Verwaltung beauftragt.",
  erledigt: "Erledigt",
  die_arbeiten_sind_abgeschlossen: "Die Arbeiten sind abgeschlossen.",
  status_ihrer_meldung: "Status Ihrer Meldung",
  terminvorschlag: "Terminvorschlag",
  der_beauftragte_betrieb_schlagt_folgende_zeiten_vor_bitt: "Der beauftragte Betrieb schlägt folgende Zeiten vor. Bitte wählen Sie einen Termin.",
  termin_bestatigt: "Termin bestätigt: ",
  keiner_passt_anderen_termin_anfragen: "Keiner passt – anderen Termin anfragen",
  abnahme: "Abnahme",
  die_arbeiten_wurden_abgeschlossen_bitte_bestatigen_sie_d: "Die Arbeiten wurden abgeschlossen. Bitte bestätigen Sie, dass alles zu Ihrer Zufriedenheit erledigt wurde.",
  ausfuhrung_abgenommen: "Ausführung abgenommen",
  ausfuhrung_abnehmen: "✓ Ausführung abnehmen",
  mangel_melden: "Mangel melden",
  dokumente: "Dokumente",
  abnahmeprotokoll_pdf: "Abnahmeprotokoll.pdf",
  abnahmeprotokoll: "Abnahmeprotokoll",
  offnen: "Öffnen",
  wie_zufrieden_waren_sie: "Wie zufrieden waren Sie?",
  ihre_ruckmeldung_geht_an_ihre_verwaltung: "Ihre Rückmeldung geht an Ihre Verwaltung.",
  optionaler_kommentar: "Optionaler Kommentar…",
  bewertung_senden: "Bewertung senden",
  hallo: "Hallo ",
  halt_sie_hier_auf_dem_laufenden: " hält Sie hier auf dem Laufenden.",
  link_nicht_verfugbar: "Link nicht verfügbar",
  dieser_melde_link_ist_ungultig_oder_wurde_deaktiviert_bi: "Dieser Melde-Link ist ungültig oder wurde deaktiviert. Bitte wenden Sie sich an Ihre Verwaltung.",
  zur_objektauswahl: "Zur Objektauswahl",
  partner: "Partner",
  partner_vor_ort: "Partner vor Ort",
  partner_signatur_zeichnen: "Bitte die Partner-Signatur zeichnen.",
  name_des_partners: "Name des Partners",
  partner_wurde_informiert: "Der Partner wurde informiert.",
} as const;

export type PortalCopyKey = keyof typeof PORTAL_COPY;

/** DE-String direkt (Katalog-Keys waren DE→EN; UI nutzt nur DE). */
export function portalCopy(key: PortalCopyKey): string {
  return PORTAL_COPY[key];
}
