/**
 * Portal-Toast-Texte — Sie-Form, ≤ 8 Wörter wo möglich.
 */
export const TOAST = {
  ablehnung_gesendet: "Ablehnung gesendet",
  aktuelles_passwort_falsch: "Aktuelles Passwort falsch.",
  akut_an_baerenwald: "Akut an Bärenwald",
  als_erledigt_gemeldet: "Als erledigt gemeldet",
  an_baerenwald_uebergeben: "An Bärenwald übergeben",
  an_die_verwaltung_zurueckgegeben: "An die Verwaltung zurückgegeben",
  aenderungen_angenommen: "Änderungen angenommen",
  aenderungen_bestaetigt: "Änderungen bestätigt",
  aenderungen_gespeichert: "Änderungen gespeichert",
  anfrage_eingereicht: "Anfrage eingereicht",
  anfrage_gesendet: "Anfrage gesendet",
  anfrage_nicht_erstellt: "Anfrage nicht erstellt",
  angaben_nicht_gespeichert: "Angaben nicht gespeichert",
  angebot_abgelehnt: "Angebot abgelehnt",
  angebot_angefordert: "Angebot angefordert",
  angebot_angenommen: "Angebot angenommen",
  angebot_eingereicht: "Angebot eingereicht",
  angebot_freigegeben: "Angebot freigegeben",
  angebot_nachziehen_fehlgeschlagen: "Angebot nachziehen fehlgeschlagen",
  angebot_nicht_automatisch_erstellt: "Angebot nicht automatisch erstellt",
  annahme_fehlgeschlagen: "Annahme fehlgeschlagen",
  auftrag_abgeschlossen: "Auftrag abgeschlossen",
  auftrag_als_erledigt_gemeldet: "Auftrag als erledigt gemeldet.",
  auftrag_angenommen: "Auftrag angenommen",
  aushang_pdf_erstellt: "Aushang-PDF erstellt",
  begruendung_mind_8_zeichen: "Begründung mind. 8 Zeichen.",
  bitte_bezeichnung_fuer_sonstiges_angeben: "Bitte Bezeichnung für Sonstiges angeben.",
  bitte_die_tatsaechliche_zeit_aufwand_auswaehlen: "Bitte die tatsächliche Zeit Aufwand auswählen.",
  bitte_ein_ende_foto_hinzufuegen: "Bitte ein Ende-Foto hinzufügen.",
  bitte_ein_start_foto_hinzufuegen: "Bitte ein Start-Foto hinzufügen.",
  bitte_eine_kurze_beschreibung_angeben: "Bitte eine kurze Beschreibung angeben.",
  daten_nicht_gespeichert: "Daten nicht gespeichert",
  dieses_dokument_kann_hier_nicht_geloescht_werden: "Dieses Dokument kann hier nicht gelöscht werden.",
  dokument_entfernt: "Dokument entfernt",
  dokument_hochgeladen: "Dokument hochgeladen",
  e_mail_fehlt: "E-Mail fehlt",
  einheit_nicht_angelegt: "Einheit nicht angelegt",
  einheit_nicht_entfernt: "Einheit nicht entfernt",
  einheit_nicht_gespeichert: "Einheit nicht gespeichert",
  einladung_erneut_gesendet: "Einladung erneut gesendet",
  einladung_erstellt: "Einladung erstellt",
  einladung_fehlgeschlagen: "Einladung fehlgeschlagen",
  einladung_nicht_erstellt: "Einladung nicht erstellt",
  einstellungen_gespeichert: "Einstellungen gespeichert",
  eintrag_geloescht: "Eintrag gelöscht",
  entfernen_fehlgeschlagen: "Entfernen fehlgeschlagen",
  export_fehlgeschlagen: "Export fehlgeschlagen",
  fachnachweis_hochgeladen: "Fachnachweis hochgeladen",
  feedback_gesendet: "Feedback gesendet",
  firmendaten_unvollstaendig: "Firmendaten unvollständig",
  foto_konnte_nicht_verarbeitet_werden_bitte_erneu: "Foto konnte nicht verarbeitet werden. Bitte erneut versuchen.",
  foto_nicht_gespeichert: "Foto nicht gespeichert",
  freigabe_abgelehnt: "Freigabe abgelehnt",
  freigabe_regeln_nicht_gespeichert: "Freigabe-Regeln nicht gespeichert",
  gesendet: "Gesendet",
  gespeichertKurz: "Gespeichert",
  gespeichert_2: "Gespeichert.",
  hausmeister_nicht_entfernt: "Hausmeister nicht entfernt",
  hausmeister_nicht_gespeichert: "Hausmeister nicht gespeichert",
  hausmeister_pruefung_gestartet: "Hausmeister-Prüfung gestartet",
  kalender_link_erstellt_in_outlook_abonnieren: "Kalender-Link erstellt — in Outlook abonnieren.",
  kalkulation_fehlgeschlagen: "Kalkulation fehlgeschlagen",
  kontakt_nicht_angelegt: "Kontakt nicht angelegt",
  kontakt_nicht_entfernt: "Kontakt nicht entfernt",
  kontakt_nicht_gespeichert: "Kontakt nicht gespeichert",
  kontakte_nicht_geladen: "Kontakte nicht geladen",
  konto_geloescht: "Konto gelöscht.",
  kopieren_fehlgeschlagen: "Kopieren fehlgeschlagen",
  kosten_konnten_nicht_geladen_werden: "Kosten konnten nicht geladen werden",
  link_kopiert: "Link kopiert",
  links_nicht_gespeichert: "Links nicht gespeichert",
  logo_nicht_gespeichert: "Logo nicht gespeichert",
  loeschen_fehlgeschlagen: "Löschen fehlgeschlagen",
  loeschen_nicht_moeglich: "Löschen nicht möglich",
  maengel_gemeldet: "Mängel gemeldet",
  meldung_abgelehnt: "Meldung abgelehnt",
  meldung_erfasst: "Meldung erfasst",
  mieter_angelegt: "Mieter angelegt",
  mindestens_eine_leistung_auswaehlen: "Mindestens eine Leistung auswählen.",
  nachtrag_eingereicht_noch_zur_pruefung_durch_bae: "Nachtrag eingereicht — noch zur Prüfung durch Bärenwald.",
  name_fehlt: "Name fehlt",
  neues_passwort_mindestens_8_zeichen: "Neues Passwort mindestens 8 Zeichen.",
  nicht_angemeldet: "Nicht angemeldet.",
  nichtGespeichert: "Nicht gespeichert",
  nur_bilder_erlaubt: "Nur Bilder erlaubt",
  objekt_angelegt: "Objekt angelegt",
  objekt_geloescht: "Objekt gelöscht",
  objekt_gespeichert: "Objekt gespeichert",
  passwort_geaendert: "Passwort geändert.",
  pdf_fehlgeschlagen: "PDF fehlgeschlagen",
  pdf_konnte_nicht_geoeffnet_werden: "PDF konnte nicht geöffnet werden",
  portal_link_bereit: "Portal-Link bereit",
  portal_link_nicht_moeglich: "Portal-Link nicht möglich",
  profil_gespeichert: "Profil gespeichert.",
  projektvertrag_bestaetigt: "Projektvertrag bestätigt",
  rahmenvertrag_bestaetigt: "Rahmenvertrag bestätigt",
  rechnung_gesendet: "Rechnung gesendet",
  rechnung_nicht_moeglich: "Rechnung nicht möglich",
  schadenmeldung_geoeffnet: "Schadenmeldung geöffnet.",
  senden_fehlgeschlagen: "Senden fehlgeschlagen",
  sofort_beauftragt: "Sofort beauftragt",
  speichern_fehlgeschlagen_bitte_erneut_versuchen: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
  stammdaten_gespeichert: "Stammdaten gespeichert",
  teilweise_nicht_geloescht: "Teilweise nicht gelöscht",
  telefon_gespeichert: "Telefon gespeichert.",
  termin_bestaetigt: "Termin bestätigt",
  testnachricht_gesendet: "Testnachricht gesendet",
  titel_mind_4_zeichen: "Titel mind. 4 Zeichen.",
  titel_text_oder_foto_angeben: "Titel, Text oder Foto angeben.",
  unterlage_nicht_gefunden: "Unterlage nicht gefunden.",
  unterlagen_hochgeladen: "Unterlagen hochgeladen",
  update_gespeichert: "Update gespeichert.",
  upload_fehlgeschlagen: "Upload fehlgeschlagen",
  versicherung_nicht_gespeichert: "Versicherung nicht gespeichert",
  versicherungsnummer_gespeichert: "Versicherungsnummer gespeichert.",
  vom_hausmeister_erledigt: "Vom Hausmeister erledigt",
  vorgang_erstellt: "Vorgang erstellt",
  vorgang_nicht_erstellt: "Vorgang nicht erstellt",
  vorgang_zurueckgezogen: "Vorgang zurückgezogen",
  zuordnung_fehlgeschlagen: "Zuordnung fehlgeschlagen",
  zuweisung_angenommen: "Zuweisung angenommen",
  speichern_fehlgeschlagen_foto: "Speichern fehlgeschlagen — Foto zu groß oder Verbindung unterbrochen. Bitte erneut versuchen.",
} as const

export type ToastKey = keyof typeof TOAST
